### PR TITLE
Add content to README.md

### PR DESCRIPTION
**Pull request by vCloudernBeer**
Add presentation outline and a brief description of the topic.

### CODE REVIEW

**Comment by rnelson0** [comment]
Anthony, are you still working on this or want it merged now?

## 

Rob Nelson
rnelson0@gmail.com

**Comment by vCloudernBeer** [comment]
I want to add an image but cannot figure out how.

How about merge this for now and if there is any changes I can submit
another change later

thanks so much,

anthony.

**Comment by rnelson0** [comment]
The syntax for an image is `alt text`

**Comment by vCloudernBeer** [comment]
cool thanks. Let me play around today and commit again.

Have a nice day.

**Comment by mbbroberg** [comment]
Keep up the great work @vCloudernBeer!

**Comment by vCloudernBeer** [comment]
Yeah, this forces me to dig deeper into this new and interesting language.

Thanks and have a nice day,

anthony.

**Pull request merged**
