### PR TITLE
Standardize challenge headers and links to videos

### PR DESCRIPTION
**Pull request by rnelson0**
Include TOC on challenge 11.

### CODE REVIEW

**Comment by rnelson0** [comment]
I recommend reviewing the changes via https://github.com/commitmas/30-days-of-commitmas-2015/pull/21/files?w=1 as something got stupid about newlines in a file.

**Comment by mbbroberg** [comment]
LGTM @rnelson0 - adding these README updates to the other challenges as they come up as well?

**Comment by rnelson0** [comment]
@mjbrender yeah, I've been getting them every day or 2. You can hit the merge button, I don't like to merge my own changes unless I have to :)

**Comment by mbbroberg** [comment]
Merging.

**Pull request merged**
