### PR TITLE
fix expert anchor & headline

### PR DESCRIPTION
**Pull request by mcamis**
headline & anchor listed "expert", copy in instructions used "Advanced"

### CODE REVIEW

**Comment by mbbroberg** [comment]
Great catch @mcamis :cake:

**Comment by mcamis** [comment]
@mjbrender heh thanks. It's very much in the spirit of this project that this was my first public pull request ever :)

**Comment by jfrappier** [comment]
Even awesomer!

**Comment by mbbroberg** [comment]
^ I love everything about that @mcamis. You'll appreciate this too @rnelson0 @bunchc

**Pull request merged**
